/**
 * This class is generated by jOOQ
 */
package com.github.fge.grappa.debugger.h2.jooq;

import com.github.fge.grappa.debugger.h2.jooq.tables.Matchers;
import com.github.fge.grappa.debugger.h2.jooq.tables.Nodes;

/**
 * Convenience access to all tables in PUBLIC
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.MATCHERS
	 */
	public static final Matchers MATCHERS = Matchers.MATCHERS;

	/**
	 * The table PUBLIC.NODES
	 */
	public static final Nodes NODES = Nodes.NODES;
}
