/**
 * This class is generated by jOOQ
 */
package com.github.fge.grappa.debugger.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.1"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Matchers extends org.jooq.impl.TableImpl<com.github.fge.grappa.debugger.db.tables.records.MatchersRecord> {

	private static final long serialVersionUID = -1843078709;

	/**
	 * The reference instance of <code>PUBLIC.MATCHERS</code>
	 */
	public static final com.github.fge.grappa.debugger.db.tables.Matchers MATCHERS = new com.github.fge.grappa.debugger.db.tables.Matchers();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.fge.grappa.debugger.db.tables.records.MatchersRecord> getRecordType() {
		return com.github.fge.grappa.debugger.db.tables.records.MatchersRecord.class;
	}

	/**
	 * The column <code>PUBLIC.MATCHERS.ID</code>.
	 */
	public final org.jooq.TableField<com.github.fge.grappa.debugger.db.tables.records.MatchersRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.MATCHERS.CLASS_NAME</code>.
	 */
	public final org.jooq.TableField<com.github.fge.grappa.debugger.db.tables.records.MatchersRecord, java.lang.String> CLASS_NAME = createField("CLASS_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.MATCHERS.MATCHER_TYPE</code>.
	 */
	public final org.jooq.TableField<com.github.fge.grappa.debugger.db.tables.records.MatchersRecord, java.lang.String> MATCHER_TYPE = createField("MATCHER_TYPE", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.MATCHERS.NAME</code>.
	 */
	public final org.jooq.TableField<com.github.fge.grappa.debugger.db.tables.records.MatchersRecord, java.lang.String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(1024).nullable(false), this, "");

	/**
	 * Create a <code>PUBLIC.MATCHERS</code> table reference
	 */
	public Matchers() {
		this("MATCHERS", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.MATCHERS</code> table reference
	 */
	public Matchers(java.lang.String alias) {
		this(alias, com.github.fge.grappa.debugger.db.tables.Matchers.MATCHERS);
	}

	private Matchers(java.lang.String alias, org.jooq.Table<com.github.fge.grappa.debugger.db.tables.records.MatchersRecord> aliased) {
		this(alias, aliased, null);
	}

	private Matchers(java.lang.String alias, org.jooq.Table<com.github.fge.grappa.debugger.db.tables.records.MatchersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.github.fge.grappa.debugger.db.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.github.fge.grappa.debugger.db.tables.records.MatchersRecord> getPrimaryKey() {
		return com.github.fge.grappa.debugger.db.Keys.CONSTRAINT_4;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.github.fge.grappa.debugger.db.tables.records.MatchersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.github.fge.grappa.debugger.db.tables.records.MatchersRecord>>asList(com.github.fge.grappa.debugger.db.Keys.CONSTRAINT_4);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.fge.grappa.debugger.db.tables.Matchers as(java.lang.String alias) {
		return new com.github.fge.grappa.debugger.db.tables.Matchers(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.github.fge.grappa.debugger.db.tables.Matchers rename(java.lang.String name) {
		return new com.github.fge.grappa.debugger.db.tables.Matchers(name, null);
	}
}
