/**
 * This class is generated by jOOQ
 */
package com.github.fge.grappa.debugger.postgresql.jooq.tables.records;

import com.github.fge.grappa.debugger.postgresql.jooq.tables.Matchers;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MatchersRecord extends org.jooq.impl.TableRecordImpl<MatchersRecord> implements org.jooq.Record5<java.util.UUID, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1336179168;

	/**
	 * Setter for <code>public.matchers.parse_info_id</code>.
	 */
	public void setParseInfoId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.matchers.parse_info_id</code>.
	 */
	public java.util.UUID getParseInfoId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.matchers.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.matchers.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.matchers.class_name</code>.
	 */
	public void setClassName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.matchers.class_name</code>.
	 */
	public java.lang.String getClassName() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.matchers.matcher_type</code>.
	 */
	public void setMatcherType(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.matchers.matcher_type</code>.
	 */
	public java.lang.String getMatcherType() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.matchers.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.matchers.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.util.UUID, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.util.UUID, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return Matchers.MATCHERS.PARSE_INFO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return Matchers.MATCHERS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return Matchers.MATCHERS.CLASS_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return Matchers.MATCHERS.MATCHER_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return Matchers.MATCHERS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getParseInfoId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getClassName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getMatcherType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MatchersRecord value1(java.util.UUID value) {
		setParseInfoId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MatchersRecord value2(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MatchersRecord value3(java.lang.String value) {
		setClassName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MatchersRecord value4(java.lang.String value) {
		setMatcherType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MatchersRecord value5(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MatchersRecord values(java.util.UUID value1, java.lang.Integer value2, java.lang.String value3, java.lang.String value4, java.lang.String value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MatchersRecord
	 */
	public MatchersRecord() {
		super(Matchers.MATCHERS);
	}

	/**
	 * Create a detached, initialised MatchersRecord
	 */
	public MatchersRecord(java.util.UUID parseInfoId, java.lang.Integer id, java.lang.String className, java.lang.String matcherType, java.lang.String name) {
		super(Matchers.MATCHERS);

		setValue(0, parseInfoId);
		setValue(1, id);
		setValue(2, className);
		setValue(3, matcherType);
		setValue(4, name);
	}
}
