/**
 * This class is generated by jOOQ
 */
package com.github.fge.grappa.debugger.postgresql.jooq;

import com.github.fge.grappa.debugger.postgresql.jooq.tables.Matchers;
import com.github.fge.grappa.debugger.postgresql.jooq.tables.Nodes;
import com.github.fge.grappa.debugger.postgresql.jooq.tables.ParseInfo;
import com.github.fge.grappa.debugger.postgresql.jooq.tables.records
	.MatchersRecord;
import com.github.fge.grappa.debugger.postgresql.jooq.tables.records.NodesRecord;
import com.github.fge.grappa.debugger.postgresql.jooq.tables.records
	.ParseInfoRecord;
import org.jooq.impl.AbstractKeys;

/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<MatchersRecord> MATCHERS_PARSE_INFO_ID_ID_KEY = UniqueKeys0.MATCHERS_PARSE_INFO_ID_ID_KEY;
	public static final org.jooq.UniqueKey<NodesRecord> NODES_PARSE_INFO_ID_ID_KEY = UniqueKeys0.NODES_PARSE_INFO_ID_ID_KEY;
	public static final org.jooq.UniqueKey<ParseInfoRecord> PARSE_INFO_PKEY = UniqueKeys0.PARSE_INFO_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<MatchersRecord, ParseInfoRecord> MATCHERS__MATCHERS_PARSE_INFO_ID_FKEY = ForeignKeys0.MATCHERS__MATCHERS_PARSE_INFO_ID_FKEY;
	public static final org.jooq.ForeignKey<NodesRecord, ParseInfoRecord> NODES__NODES_PARSE_INFO_ID_FKEY = ForeignKeys0.NODES__NODES_PARSE_INFO_ID_FKEY;
	public static final org.jooq.ForeignKey<NodesRecord, MatchersRecord> NODES__NODES_PARSE_INFO_ID_FKEY1 = ForeignKeys0.NODES__NODES_PARSE_INFO_ID_FKEY1;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<MatchersRecord> MATCHERS_PARSE_INFO_ID_ID_KEY = createUniqueKey(
			Matchers.MATCHERS, Matchers.MATCHERS.PARSE_INFO_ID, Matchers.MATCHERS.ID);
		public static final org.jooq.UniqueKey<NodesRecord> NODES_PARSE_INFO_ID_ID_KEY = createUniqueKey(
			Nodes.NODES, Nodes.NODES.PARSE_INFO_ID, Nodes.NODES.ID);
		public static final org.jooq.UniqueKey<ParseInfoRecord> PARSE_INFO_PKEY = createUniqueKey(
			ParseInfo.PARSE_INFO, ParseInfo.PARSE_INFO.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<MatchersRecord, ParseInfoRecord> MATCHERS__MATCHERS_PARSE_INFO_ID_FKEY = AbstractKeys

			.createForeignKey(Keys.PARSE_INFO_PKEY, Matchers.MATCHERS,
				Matchers.MATCHERS.PARSE_INFO_ID);
		public static final org.jooq.ForeignKey<NodesRecord, ParseInfoRecord> NODES__NODES_PARSE_INFO_ID_FKEY = AbstractKeys
			.createForeignKey(Keys.PARSE_INFO_PKEY,
				Nodes
					.NODES,
				Nodes.NODES.PARSE_INFO_ID);
		public static final org.jooq.ForeignKey<NodesRecord, MatchersRecord> NODES__NODES_PARSE_INFO_ID_FKEY1 = AbstractKeys
			.createForeignKey(Keys.MATCHERS_PARSE_INFO_ID_ID_KEY,
				Nodes
					.NODES,
				Nodes
					.NODES.PARSE_INFO_ID,
				Nodes.NODES.MATCHER_ID);
	}
}
