/**
 * This class is generated by jOOQ
 */
package com.github.fge.grappa.debugger.jooq.h2.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Nodes extends org.jooq.impl.TableImpl<com.github.fge.grappa.debugger.jooq.h2.tables.records.NodesRecord> {

	private static final long serialVersionUID = -1216060393;

	/**
	 * The reference instance of <code>PUBLIC.NODES</code>
	 */
	public static final com.github.fge.grappa.debugger.jooq.h2.tables.Nodes NODES = new com.github.fge.grappa.debugger.jooq.h2.tables.Nodes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.fge.grappa.debugger.jooq.h2.tables.records.NodesRecord> getRecordType() {
		return com.github.fge.grappa.debugger.jooq.h2.tables.records.NodesRecord.class;
	}

	/**
	 * The column <code>PUBLIC.NODES.ID</code>.
	 */
	public final org.jooq.TableField<com.github.fge.grappa.debugger.jooq.h2.tables.records.NodesRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.NODES.PARENT_ID</code>.
	 */
	public final org.jooq.TableField<com.github.fge.grappa.debugger.jooq.h2.tables.records.NodesRecord, java.lang.Integer> PARENT_ID = createField("PARENT_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.NODES.LEVEL</code>.
	 */
	public final org.jooq.TableField<com.github.fge.grappa.debugger.jooq.h2.tables.records.NodesRecord, java.lang.Integer> LEVEL = createField("LEVEL", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.NODES.SUCCESS</code>.
	 */
	public final org.jooq.TableField<com.github.fge.grappa.debugger.jooq.h2.tables.records.NodesRecord, java.lang.Integer> SUCCESS = createField("SUCCESS", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.NODES.MATCHER_ID</code>.
	 */
	public final org.jooq.TableField<com.github.fge.grappa.debugger.jooq.h2.tables.records.NodesRecord, java.lang.Integer> MATCHER_ID = createField("MATCHER_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.NODES.START_INDEX</code>.
	 */
	public final org.jooq.TableField<com.github.fge.grappa.debugger.jooq.h2.tables.records.NodesRecord, java.lang.Integer> START_INDEX = createField("START_INDEX", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.NODES.END_INDEX</code>.
	 */
	public final org.jooq.TableField<com.github.fge.grappa.debugger.jooq.h2.tables.records.NodesRecord, java.lang.Integer> END_INDEX = createField("END_INDEX", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.NODES.TIME</code>.
	 */
	public final org.jooq.TableField<com.github.fge.grappa.debugger.jooq.h2.tables.records.NodesRecord, java.lang.Long> TIME = createField("TIME", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>PUBLIC.NODES</code> table reference
	 */
	public Nodes() {
		this("NODES", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.NODES</code> table reference
	 */
	public Nodes(java.lang.String alias) {
		this(alias, com.github.fge.grappa.debugger.jooq.h2.tables.Nodes.NODES);
	}

	private Nodes(java.lang.String alias, org.jooq.Table<com.github.fge.grappa.debugger.jooq.h2.tables.records.NodesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Nodes(java.lang.String alias, org.jooq.Table<com.github.fge.grappa.debugger.jooq.h2.tables.records.NodesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.github.fge.grappa.debugger.jooq.h2.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.github.fge.grappa.debugger.jooq.h2.tables.records.NodesRecord> getPrimaryKey() {
		return com.github.fge.grappa.debugger.jooq.h2.Keys.CONSTRAINT_47;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.github.fge.grappa.debugger.jooq.h2.tables.records.NodesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.github.fge.grappa.debugger.jooq.h2.tables.records.NodesRecord>>asList(com.github.fge.grappa.debugger.jooq.h2.Keys.CONSTRAINT_47);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.github.fge.grappa.debugger.jooq.h2.tables.records.NodesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.github.fge.grappa.debugger.jooq.h2.tables.records.NodesRecord, ?>>asList(com.github.fge.grappa.debugger.jooq.h2.Keys.CONSTRAINT_470);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.fge.grappa.debugger.jooq.h2.tables.Nodes as(java.lang.String alias) {
		return new com.github.fge.grappa.debugger.jooq.h2.tables.Nodes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.github.fge.grappa.debugger.jooq.h2.tables.Nodes rename(java.lang.String name) {
		return new com.github.fge.grappa.debugger.jooq.h2.tables.Nodes(name, null);
	}
}
