/**
 * This class is generated by jOOQ
 */
package com.github.fge.grappa.debugger.h2.jooq.tables;

import com.github.fge.grappa.debugger.h2.jooq.Keys;
import com.github.fge.grappa.debugger.h2.jooq.Public;
import com.github.fge.grappa.debugger.h2.jooq.tables.records.NodesRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Nodes extends org.jooq.impl.TableImpl<NodesRecord> {

	private static final long serialVersionUID = -1216060393;

	/**
	 * The reference instance of <code>PUBLIC.NODES</code>
	 */
	public static final Nodes NODES = new Nodes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<NodesRecord> getRecordType() {
		return NodesRecord.class;
	}

	/**
	 * The column <code>PUBLIC.NODES.ID</code>.
	 */
	public final org.jooq.TableField<NodesRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.NODES.PARENT_ID</code>.
	 */
	public final org.jooq.TableField<NodesRecord, java.lang.Integer> PARENT_ID = createField("PARENT_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.NODES.LEVEL</code>.
	 */
	public final org.jooq.TableField<NodesRecord, java.lang.Integer> LEVEL = createField("LEVEL", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.NODES.SUCCESS</code>.
	 */
	public final org.jooq.TableField<NodesRecord, java.lang.Integer> SUCCESS = createField("SUCCESS", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.NODES.MATCHER_ID</code>.
	 */
	public final org.jooq.TableField<NodesRecord, java.lang.Integer> MATCHER_ID = createField("MATCHER_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.NODES.START_INDEX</code>.
	 */
	public final org.jooq.TableField<NodesRecord, java.lang.Integer> START_INDEX = createField("START_INDEX", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.NODES.END_INDEX</code>.
	 */
	public final org.jooq.TableField<NodesRecord, java.lang.Integer> END_INDEX = createField("END_INDEX", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.NODES.TIME</code>.
	 */
	public final org.jooq.TableField<NodesRecord, java.lang.Long> TIME = createField("TIME", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>PUBLIC.NODES</code> table reference
	 */
	public Nodes() {
		this("NODES", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.NODES</code> table reference
	 */
	public Nodes(java.lang.String alias) {
		this(alias, Nodes.NODES);
	}

	private Nodes(java.lang.String alias, org.jooq.Table<NodesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Nodes(java.lang.String alias, org.jooq.Table<NodesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<NodesRecord> getPrimaryKey() {
		return Keys.CONSTRAINT_47;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<NodesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<NodesRecord>>asList(
			Keys.CONSTRAINT_47);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<NodesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<NodesRecord, ?>>asList(
			Keys.CONSTRAINT_470);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Nodes as(java.lang.String alias) {
		return new Nodes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Nodes rename(java.lang.String name) {
		return new Nodes(name, null);
	}
}
