/**
 * This class is generated by jOOQ
 */
package com.github.fge.grappa.debugger.jooq.postgresql;

/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.MatchersRecord> MATCHERS_PARSE_INFO_ID_ID_KEY = UniqueKeys0.MATCHERS_PARSE_INFO_ID_ID_KEY;
	public static final org.jooq.UniqueKey<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.NodesRecord> NODES_PARSE_INFO_ID_ID_KEY = UniqueKeys0.NODES_PARSE_INFO_ID_ID_KEY;
	public static final org.jooq.UniqueKey<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.ParseInfoRecord> PARSE_INFO_PKEY = UniqueKeys0.PARSE_INFO_PKEY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.MatchersRecord, com.github.fge.grappa.debugger.jooq.postgresql.tables.records.ParseInfoRecord> MATCHERS__MATCHERS_PARSE_INFO_ID_FKEY = ForeignKeys0.MATCHERS__MATCHERS_PARSE_INFO_ID_FKEY;
	public static final org.jooq.ForeignKey<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.NodesRecord, com.github.fge.grappa.debugger.jooq.postgresql.tables.records.ParseInfoRecord> NODES__NODES_PARSE_INFO_ID_FKEY = ForeignKeys0.NODES__NODES_PARSE_INFO_ID_FKEY;
	public static final org.jooq.ForeignKey<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.NodesRecord, com.github.fge.grappa.debugger.jooq.postgresql.tables.records.MatchersRecord> NODES__NODES_PARSE_INFO_ID_FKEY1 = ForeignKeys0.NODES__NODES_PARSE_INFO_ID_FKEY1;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.MatchersRecord> MATCHERS_PARSE_INFO_ID_ID_KEY = createUniqueKey(com.github.fge.grappa.debugger.jooq.postgresql.tables.Matchers.MATCHERS, com.github.fge.grappa.debugger.jooq.postgresql.tables.Matchers.MATCHERS.PARSE_INFO_ID, com.github.fge.grappa.debugger.jooq.postgresql.tables.Matchers.MATCHERS.ID);
		public static final org.jooq.UniqueKey<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.NodesRecord> NODES_PARSE_INFO_ID_ID_KEY = createUniqueKey(com.github.fge.grappa.debugger.jooq.postgresql.tables.Nodes.NODES, com.github.fge.grappa.debugger.jooq.postgresql.tables.Nodes.NODES.PARSE_INFO_ID, com.github.fge.grappa.debugger.jooq.postgresql.tables.Nodes.NODES.ID);
		public static final org.jooq.UniqueKey<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.ParseInfoRecord> PARSE_INFO_PKEY = createUniqueKey(com.github.fge.grappa.debugger.jooq.postgresql.tables.ParseInfo.PARSE_INFO, com.github.fge.grappa.debugger.jooq.postgresql.tables.ParseInfo.PARSE_INFO.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.MatchersRecord, com.github.fge.grappa.debugger.jooq.postgresql.tables.records.ParseInfoRecord> MATCHERS__MATCHERS_PARSE_INFO_ID_FKEY = createForeignKey(com.github.fge.grappa.debugger.jooq.postgresql.Keys.PARSE_INFO_PKEY, com.github.fge.grappa.debugger.jooq.postgresql.tables.Matchers.MATCHERS, com.github.fge.grappa.debugger.jooq.postgresql.tables.Matchers.MATCHERS.PARSE_INFO_ID);
		public static final org.jooq.ForeignKey<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.NodesRecord, com.github.fge.grappa.debugger.jooq.postgresql.tables.records.ParseInfoRecord> NODES__NODES_PARSE_INFO_ID_FKEY = createForeignKey(com.github.fge.grappa.debugger.jooq.postgresql.Keys.PARSE_INFO_PKEY, com.github.fge.grappa.debugger.jooq.postgresql.tables.Nodes.NODES, com.github.fge.grappa.debugger.jooq.postgresql.tables.Nodes.NODES.PARSE_INFO_ID);
		public static final org.jooq.ForeignKey<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.NodesRecord, com.github.fge.grappa.debugger.jooq.postgresql.tables.records.MatchersRecord> NODES__NODES_PARSE_INFO_ID_FKEY1 = createForeignKey(com.github.fge.grappa.debugger.jooq.postgresql.Keys.MATCHERS_PARSE_INFO_ID_ID_KEY, com.github.fge.grappa.debugger.jooq.postgresql.tables.Nodes.NODES, com.github.fge.grappa.debugger.jooq.postgresql.tables.Nodes.NODES.PARSE_INFO_ID, com.github.fge.grappa.debugger.jooq.postgresql.tables.Nodes.NODES.MATCHER_ID);
	}
}
