/**
 * This class is generated by jOOQ
 */
package com.github.fge.grappa.debugger.jooq.postgresql;

/**
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.matchers
	 */
	public static final com.github.fge.grappa.debugger.jooq.postgresql.tables.Matchers MATCHERS = com.github.fge.grappa.debugger.jooq.postgresql.tables.Matchers.MATCHERS;

	/**
	 * The table public.nodes
	 */
	public static final com.github.fge.grappa.debugger.jooq.postgresql.tables.Nodes NODES = com.github.fge.grappa.debugger.jooq.postgresql.tables.Nodes.NODES;

	/**
	 * The table public.parse_info
	 */
	public static final com.github.fge.grappa.debugger.jooq.postgresql.tables.ParseInfo PARSE_INFO = com.github.fge.grappa.debugger.jooq.postgresql.tables.ParseInfo.PARSE_INFO;
}
