/**
 * This class is generated by jOOQ
 */
package com.github.fge.grappa.debugger.jooq.postgresql.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NodesRecord extends org.jooq.impl.TableRecordImpl<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.NodesRecord> implements org.jooq.Record9<java.util.UUID, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Long> {

	private static final long serialVersionUID = -1625460392;

	/**
	 * Setter for <code>public.nodes.parse_info_id</code>.
	 */
	public void setParseInfoId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.nodes.parse_info_id</code>.
	 */
	public java.util.UUID getParseInfoId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.nodes.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.nodes.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>public.nodes.parent_id</code>.
	 */
	public void setParentId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.nodes.parent_id</code>.
	 */
	public java.lang.Integer getParentId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>public.nodes.level</code>.
	 */
	public void setLevel(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.nodes.level</code>.
	 */
	public java.lang.Integer getLevel() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>public.nodes.success</code>.
	 */
	public void setSuccess(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.nodes.success</code>.
	 */
	public java.lang.Integer getSuccess() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>public.nodes.matcher_id</code>.
	 */
	public void setMatcherId(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.nodes.matcher_id</code>.
	 */
	public java.lang.Integer getMatcherId() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>public.nodes.start_index</code>.
	 */
	public void setStartIndex(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.nodes.start_index</code>.
	 */
	public java.lang.Integer getStartIndex() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>public.nodes.end_index</code>.
	 */
	public void setEndIndex(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.nodes.end_index</code>.
	 */
	public java.lang.Integer getEndIndex() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>public.nodes.time</code>.
	 */
	public void setTime(java.lang.Long value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.nodes.time</code>.
	 */
	public java.lang.Long getTime() {
		return (java.lang.Long) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.util.UUID, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Long> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.util.UUID, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Long> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return com.github.fge.grappa.debugger.jooq.postgresql.tables.Nodes.NODES.PARSE_INFO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.github.fge.grappa.debugger.jooq.postgresql.tables.Nodes.NODES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.github.fge.grappa.debugger.jooq.postgresql.tables.Nodes.NODES.PARENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return com.github.fge.grappa.debugger.jooq.postgresql.tables.Nodes.NODES.LEVEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return com.github.fge.grappa.debugger.jooq.postgresql.tables.Nodes.NODES.SUCCESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return com.github.fge.grappa.debugger.jooq.postgresql.tables.Nodes.NODES.MATCHER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return com.github.fge.grappa.debugger.jooq.postgresql.tables.Nodes.NODES.START_INDEX;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return com.github.fge.grappa.debugger.jooq.postgresql.tables.Nodes.NODES.END_INDEX;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field9() {
		return com.github.fge.grappa.debugger.jooq.postgresql.tables.Nodes.NODES.TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getParseInfoId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getParentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getLevel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getSuccess();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getMatcherId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getStartIndex();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getEndIndex();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value9() {
		return getTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NodesRecord value1(java.util.UUID value) {
		setParseInfoId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NodesRecord value2(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NodesRecord value3(java.lang.Integer value) {
		setParentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NodesRecord value4(java.lang.Integer value) {
		setLevel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NodesRecord value5(java.lang.Integer value) {
		setSuccess(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NodesRecord value6(java.lang.Integer value) {
		setMatcherId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NodesRecord value7(java.lang.Integer value) {
		setStartIndex(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NodesRecord value8(java.lang.Integer value) {
		setEndIndex(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NodesRecord value9(java.lang.Long value) {
		setTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public NodesRecord values(java.util.UUID value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.Integer value4, java.lang.Integer value5, java.lang.Integer value6, java.lang.Integer value7, java.lang.Integer value8, java.lang.Long value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached NodesRecord
	 */
	public NodesRecord() {
		super(com.github.fge.grappa.debugger.jooq.postgresql.tables.Nodes.NODES);
	}

	/**
	 * Create a detached, initialised NodesRecord
	 */
	public NodesRecord(java.util.UUID parseInfoId, java.lang.Integer id, java.lang.Integer parentId, java.lang.Integer level, java.lang.Integer success, java.lang.Integer matcherId, java.lang.Integer startIndex, java.lang.Integer endIndex, java.lang.Long time) {
		super(com.github.fge.grappa.debugger.jooq.postgresql.tables.Nodes.NODES);

		setValue(0, parseInfoId);
		setValue(1, id);
		setValue(2, parentId);
		setValue(3, level);
		setValue(4, success);
		setValue(5, matcherId);
		setValue(6, startIndex);
		setValue(7, endIndex);
		setValue(8, time);
	}
}
