/**
 * This class is generated by jOOQ
 */
package com.github.fge.grappa.debugger.jooq.postgresql.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParseInfoRecord extends org.jooq.impl.UpdatableRecordImpl<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.ParseInfoRecord> implements org.jooq.Record3<java.util.UUID, java.sql.Timestamp, java.lang.String> {

	private static final long serialVersionUID = 1036128975;

	/**
	 * Setter for <code>public.parse_info.id</code>.
	 */
	public void setId(java.util.UUID value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.parse_info.id</code>.
	 */
	public java.util.UUID getId() {
		return (java.util.UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.parse_info.date</code>.
	 */
	public void setDate(java.sql.Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.parse_info.date</code>.
	 */
	public java.sql.Timestamp getDate() {
		return (java.sql.Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>public.parse_info.content</code>.
	 */
	public void setContent(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.parse_info.content</code>.
	 */
	public java.lang.String getContent() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.util.UUID> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.util.UUID, java.sql.Timestamp, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.util.UUID, java.sql.Timestamp, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.util.UUID> field1() {
		return com.github.fge.grappa.debugger.jooq.postgresql.tables.ParseInfo.PARSE_INFO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field2() {
		return com.github.fge.grappa.debugger.jooq.postgresql.tables.ParseInfo.PARSE_INFO.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.github.fge.grappa.debugger.jooq.postgresql.tables.ParseInfo.PARSE_INFO.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.UUID value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value2() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ParseInfoRecord value1(java.util.UUID value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ParseInfoRecord value2(java.sql.Timestamp value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ParseInfoRecord value3(java.lang.String value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ParseInfoRecord values(java.util.UUID value1, java.sql.Timestamp value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ParseInfoRecord
	 */
	public ParseInfoRecord() {
		super(com.github.fge.grappa.debugger.jooq.postgresql.tables.ParseInfo.PARSE_INFO);
	}

	/**
	 * Create a detached, initialised ParseInfoRecord
	 */
	public ParseInfoRecord(java.util.UUID id, java.sql.Timestamp date, java.lang.String content) {
		super(com.github.fge.grappa.debugger.jooq.postgresql.tables.ParseInfo.PARSE_INFO);

		setValue(0, id);
		setValue(1, date);
		setValue(2, content);
	}
}
