/**
 * This class is generated by jOOQ
 */
package com.github.fge.grappa.debugger.jooq.h2;

/**
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> 
 * schema
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.github.fge.grappa.debugger.jooq.h2.tables.records.MatchersRecord> CONSTRAINT_4 = UniqueKeys0.CONSTRAINT_4;
	public static final org.jooq.UniqueKey<com.github.fge.grappa.debugger.jooq.h2.tables.records.NodesRecord> CONSTRAINT_47 = UniqueKeys0.CONSTRAINT_47;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<com.github.fge.grappa.debugger.jooq.h2.tables.records.NodesRecord, com.github.fge.grappa.debugger.jooq.h2.tables.records.MatchersRecord> CONSTRAINT_470 = ForeignKeys0.CONSTRAINT_470;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.github.fge.grappa.debugger.jooq.h2.tables.records.MatchersRecord> CONSTRAINT_4 = createUniqueKey(com.github.fge.grappa.debugger.jooq.h2.tables.Matchers.MATCHERS, com.github.fge.grappa.debugger.jooq.h2.tables.Matchers.MATCHERS.ID);
		public static final org.jooq.UniqueKey<com.github.fge.grappa.debugger.jooq.h2.tables.records.NodesRecord> CONSTRAINT_47 = createUniqueKey(com.github.fge.grappa.debugger.jooq.h2.tables.Nodes.NODES, com.github.fge.grappa.debugger.jooq.h2.tables.Nodes.NODES.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<com.github.fge.grappa.debugger.jooq.h2.tables.records.NodesRecord, com.github.fge.grappa.debugger.jooq.h2.tables.records.MatchersRecord> CONSTRAINT_470 = createForeignKey(com.github.fge.grappa.debugger.jooq.h2.Keys.CONSTRAINT_4, com.github.fge.grappa.debugger.jooq.h2.tables.Nodes.NODES, com.github.fge.grappa.debugger.jooq.h2.tables.Nodes.NODES.MATCHER_ID);
	}
}
