/**
 * This class is generated by jOOQ
 */
package com.github.fge.grappa.debugger.jooq.h2;

/**
 * Convenience access to all tables in PUBLIC
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.MATCHERS
	 */
	public static final com.github.fge.grappa.debugger.jooq.h2.tables.Matchers MATCHERS = com.github.fge.grappa.debugger.jooq.h2.tables.Matchers.MATCHERS;

	/**
	 * The table PUBLIC.NODES
	 */
	public static final com.github.fge.grappa.debugger.jooq.h2.tables.Nodes NODES = com.github.fge.grappa.debugger.jooq.h2.tables.Nodes.NODES;
}
