/**
 * This class is generated by jOOQ
 */
package com.github.fge.grappa.debugger.jooq.postgresql.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Matchers extends org.jooq.impl.TableImpl<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.MatchersRecord> {

	private static final long serialVersionUID = 1428262879;

	/**
	 * The reference instance of <code>public.matchers</code>
	 */
	public static final com.github.fge.grappa.debugger.jooq.postgresql.tables.Matchers MATCHERS = new com.github.fge.grappa.debugger.jooq.postgresql.tables.Matchers();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.MatchersRecord> getRecordType() {
		return com.github.fge.grappa.debugger.jooq.postgresql.tables.records.MatchersRecord.class;
	}

	/**
	 * The column <code>public.matchers.parse_info_id</code>.
	 */
	public final org.jooq.TableField<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.MatchersRecord, java.util.UUID> PARSE_INFO_ID = createField("parse_info_id", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>public.matchers.id</code>.
	 */
	public final org.jooq.TableField<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.MatchersRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>public.matchers.class_name</code>.
	 */
	public final org.jooq.TableField<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.MatchersRecord, java.lang.String> CLASS_NAME = createField("class_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>public.matchers.matcher_type</code>.
	 */
	public final org.jooq.TableField<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.MatchersRecord, java.lang.String> MATCHER_TYPE = createField("matcher_type", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

	/**
	 * The column <code>public.matchers.name</code>.
	 */
	public final org.jooq.TableField<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.MatchersRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(1024).nullable(false), this, "");

	/**
	 * Create a <code>public.matchers</code> table reference
	 */
	public Matchers() {
		this("matchers", null);
	}

	/**
	 * Create an aliased <code>public.matchers</code> table reference
	 */
	public Matchers(java.lang.String alias) {
		this(alias, com.github.fge.grappa.debugger.jooq.postgresql.tables.Matchers.MATCHERS);
	}

	private Matchers(java.lang.String alias, org.jooq.Table<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.MatchersRecord> aliased) {
		this(alias, aliased, null);
	}

	private Matchers(java.lang.String alias, org.jooq.Table<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.MatchersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.github.fge.grappa.debugger.jooq.postgresql.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.MatchersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.MatchersRecord>>asList(com.github.fge.grappa.debugger.jooq.postgresql.Keys.MATCHERS_PARSE_INFO_ID_ID_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.MatchersRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.github.fge.grappa.debugger.jooq.postgresql.tables.records.MatchersRecord, ?>>asList(com.github.fge.grappa.debugger.jooq.postgresql.Keys.MATCHERS__MATCHERS_PARSE_INFO_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.fge.grappa.debugger.jooq.postgresql.tables.Matchers as(java.lang.String alias) {
		return new com.github.fge.grappa.debugger.jooq.postgresql.tables.Matchers(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.github.fge.grappa.debugger.jooq.postgresql.tables.Matchers rename(java.lang.String name) {
		return new com.github.fge.grappa.debugger.jooq.postgresql.tables.Matchers(name, null);
	}
}
